apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flais.yaml
  - vigo-oauth2-client.yaml
  - hmsreg-oauth2-client.yaml
  - altinn-onepassword.yaml
  - egrunnerverv-onepassword.yaml
  - isygraving-oauth2-client.yaml